### ISSUE TITLE
请教几个应用的区别说明

### ISSUE THREAD

**Issue by lslzl3000** [devsapp/fc-llm#1]
感谢，这几天一直在想用fc部署llama2，刚发现官方也在做
有一个问题，目前的应用:
- pg-chatglm2-6b
- chatglm2-6b
- chatglm2-6b-api

具体什么区别呢？用法有什么不同
我看项目一直在更新，目前是可以部署使用吗？还是需要再等等？

**Comment by lslzl3000** [comment]
后续会更新 readme 详细介绍安装，部署和使用吗？

**Comment by hanxie-crypto** [comment]
是的，正在写教程，目前chatglm2-6b 和 chatglm2-6b-int的模型都是可用了，llama2还在调，要等一下，pg-chatglm2-6b是使用阿里云pg数据库做向量的问答项目，chatglm2-6b 是开源 chatglm2-6b的托管 ，chatglm2-6b-api是我们提供的api

**Comment by lslzl3000** [comment]
请教一下，用 `s` 命令行进行部署，成功后，无法通过 log 中 `fcapp.fun` 的阿里fc的域名进行访问，必须使用 log 中 custom domain `fc.devsapp.net` 进行访问
是需要什么特殊的设置吗？
